services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: finance.kayarn.co
    hostname: finance.kayarn.co
    expose:
      - 5006
    volumes:
      - ./actual-data:/data
    restart: unless-stopped
    networks:
      - travel
  
networks:
  travel:
    external: true
